#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
# -----------------------------------------------------------------------------

if [ ! -f /data/minecraft_server.jar ]
then
    curl "https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar" -o /data/minecraft_server.jar
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -server -Xms512M -Xmx2048M -jar minecraft_server.jar nogui
